services:
  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: ${HOSTNAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_CERT_DOMAIN=${HOSTNAME}
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - ${PWD}/serve.json:/config/serve.json
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale-nginx
    volumes:
      - ${PWD}/bash:/usr/share/nginx/html:ro
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: service:tailscale-nginx
